% Copyright 2022-2023 the Tectonic Project
% Licensed under the MIT License
%
% Tectonopedia document class
%
\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\ProvidesClass{pedia}[2022/10/30 Tectonopedia document class]
%
\ExecuteOptions{}
\ProcessOptions
%
\LoadClass{article}
%
\input{pedia/fonts.tex}
\input{pedia/tdux_lowlevel.tex}
\input{pedia/at_escaping.tex}
\input{pedia/links.tex}
\input{pedia/crossrefs.tex}
\input{pedia/templates.tex}
\input{pedia/metadata.tex}
\input{pedia/verbatim.tex}
\input{pedia/terms.tex}
\input{pedia/typography.tex}
\input{pedia/tex_code.tex}
\input{pedia/sectioning.tex}
\input{pedia/lists.tex}
\input{pedia/outputs.tex}
\input{pedia/entries.tex}
\input{pedia/explainers.tex}
