# Copyright 2023 the Tectonic Project
# Licensed under the MIT License.
#
# Main pipeline spec for CI/CD on Azure Pipelines.

trigger:
  branches:
    include:
    - master
    - rc

stages:
- stage: Prep
  jobs:
  - template: azure-prep.yml

- stage: BuildAndTest
  jobs:
  - template: azure-build-and-test.yml

- stage: Deploy
  condition: and(succeeded('BuildAndTest'), ne(variables['build.reason'], 'PullRequest'))
  jobs:
  - template: azure-deployment.yml
    parameters:
      isMainDev: ${{ eq(variables['Build.SourceBranchName'], 'master') }}
      isRelease: ${{ eq(variables['Build.SourceBranchName'], 'rc') }}
